-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgVH4SuftpagnMdC/3
KCx5lrUdwMBZstqRtrdwvg9F3XSgCgYIKoZIzj0DAQehRANCAASF4xvgDkzG0hXk
XdjeqEr5TZHYKBEIzQB6irDNItMAvxhr6EdvaYfoM1kfSSa9o7+wUKHREbejR2hg
fFgFYari
-----END PRIVATE KEY-----