# Uncomment the next line to define a global platform for your project
platform :ios, '15.0'

target 'Daily Rota' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Daily Rota
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'Firebase/Storage'
  pod 'FirebaseFirestoreSwift'
  
  # Optional: Add these if you need them
  # pod 'Firebase/Analytics'
  # pod 'Firebase/Messaging' # For push notifications
  
end 